export { h } from './h'
export { renderSlot } from './helpers/renderSlot'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { provide, inject } from './apiInject'
export { createRenderer } from './renderer'
export { nextTick } from './scheduler'
export * from '../reactivity'
